// packages/game-core/src/network-types.ts
// PATCHED: see comment [FIX #2] on AttackPrepEvent

import type { Board, Coordinate, GamePhase, Missile } from "./types";

// ── Morse primitives ──────────────────────────────────────────────────────────

export type MorseSymbol = "." | "-";

export type MorseSequence = MorseSymbol[];

// ── Event-type registry ───────────────────────────────────────────────────────

export const GameEventType = {
  JOIN_ROOM: "JOIN_ROOM",
  SHIPS_PLACED: "SHIPS_PLACED",
  ATTACK_PREP: "ATTACK_PREP",
  MISSILE_LAUNCHED: "MISSILE_LAUNCHED",
  INTERCEPT_ATTEMPT: "INTERCEPT_ATTEMPT",
  PLAYER_JOINED: "PLAYER_JOINED",
  GAME_STARTED: "GAME_STARTED",
  INCOMING_MISSILE: "INCOMING_MISSILE",
  RESOLVE_HIT: "RESOLVE_HIT",
  SYNC_STATE: "SYNC_STATE",
  ERROR: "ERROR",
} as const;

export type GameEventType = (typeof GameEventType)[keyof typeof GameEventType];

// ── Per-event payload types ───────────────────────────────────────────────────

export type JoinRoomEvent = {
  type: typeof GameEventType.JOIN_ROOM;
  payload: {
    playerId: string;
    playerName: string;
  };
};

export type ShipsPlacedEvent = {
  type: typeof GameEventType.SHIPS_PLACED;
  payload: {
    ships: ReadonlyArray<{ coords: readonly Coordinate[] }>;
  };
};

// [FIX #2] — added `missileId` to AttackPrepEvent payload.
//
// The server's #handleAttackPrep handler reads BOTH `target` and `missileId`
// from the payload and passes them to prepareAttack(). Without `missileId`
// in the type, any client following the type contract would omit it, causing
// the server to return INVALID_COORDINATE on every ATTACK_PREP — making the
// battle phase permanently broken.
export type AttackPrepEvent = {
  type: typeof GameEventType.ATTACK_PREP;
  payload: {
    /** The cell the attacker intends to fire at. */
    target: Coordinate;
    /**
     * Stable UUID generated by the attacker.
     * Sent here so the server can lock it in PendingAttack; the same ID must
     * be echoed back in the subsequent MISSILE_LAUNCHED event.
     */
    missileId: string;
  };
};

export type MissileLaunchedEvent = {
  type: typeof GameEventType.MISSILE_LAUNCHED;
  payload: {
    missileId: string;
    target: Coordinate;
    morseSequence: MorseSequence;
    timestamp: number;
  };
};

export type InterceptAttemptEvent = {
  type: typeof GameEventType.INTERCEPT_ATTEMPT;
  payload: {
    missileId: string;
    decodedCoord: Coordinate;
    attemptNumber: number;
  };
};

export type PlayerJoinedEvent = {
  type: typeof GameEventType.PLAYER_JOINED;
  payload: {
    playerId: string;
    playerName: string;
    playerCount: 1 | 2;
  };
};

export type GameStartedEvent = {
  type: typeof GameEventType.GAME_STARTED;
  payload: {
    firstTurnPlayerId: string;
  };
};

export type IncomingMissileEvent = {
  type: typeof GameEventType.INCOMING_MISSILE;
  payload: {
    missileId: string;
    morseSequence: MorseSequence;
    timestamp: number;
    maxAttempts: number;
  };
};

export type HitResult = "hit" | "miss" | "sunk";

export type ResolveHitEvent = {
  type: typeof GameEventType.RESOLVE_HIT;
  payload: {
    missileId: string;
    target: Coordinate;
    result: HitResult;
    nextTurnPlayerId: string;
    isGameOver: boolean;
    winnerId?: string | undefined;
    defenderDecodedCorrectly: boolean;
  };
};

export type SyncStateEvent = {
  type: typeof GameEventType.SYNC_STATE;
  payload: {
    phase: GamePhase;
    ownBoard: Board;
    enemyBoard: Board;
    activeMissiles: Missile[];
    isMyTurn: boolean;
    winnerId?: string | undefined;
  };
};

export type ErrorEvent = {
  type: typeof GameEventType.ERROR;
  payload: {
    code: ErrorCode;
    message: string;
  };
};

// ── Error codes ───────────────────────────────────────────────────────────────

export const ErrorCode = {
  ROOM_FULL: "ROOM_FULL",
  INVALID_PLACEMENT: "INVALID_PLACEMENT",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  CELL_ALREADY_SHOT: "CELL_ALREADY_SHOT",
  MORSE_MISMATCH: "MORSE_MISMATCH",
  INVALID_COORDINATE: "INVALID_COORDINATE",
  MAX_ATTEMPTS_REACHED: "MAX_ATTEMPTS_REACHED",
  GAME_NOT_STARTED: "GAME_NOT_STARTED",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// ── Discriminated unions ──────────────────────────────────────────────────────

export type ClientGameEvent =
  | JoinRoomEvent
  | ShipsPlacedEvent
  | AttackPrepEvent
  | MissileLaunchedEvent
  | InterceptAttemptEvent;

export type ServerGameEvent =
  | PlayerJoinedEvent
  | GameStartedEvent
  | IncomingMissileEvent
  | ResolveHitEvent
  | SyncStateEvent
  | ErrorEvent;

export type GameEvent = ClientGameEvent | ServerGameEvent;
